version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels: ["topic: build"]
    schedule:
      interval: weekly
      day: sunday
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels: ["topic: CI/CD"]
    schedule:
      interval: weekly
      day: sunday
    groups:
      github-actions:
        patterns:
          - "*"
