name: 🚀 Feature request
description: Submit a proposal/request for a new feature for OnnxTR. Please search for existing issues before creating a new one.
labels: 'type: enhancement'

body:
- type: textarea
  attributes:
    label: 🚀 The feature
    description: >
      A clear and concise description of the feature proposal
  validations:
    required: true
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉
