name: docker

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  docker-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build docker image
        run: docker build -t doctr-tf-py3.9-slim --build-arg SYSTEM=cpu .
      - name: Run docker container
        run: docker run doctr-tf-py3.9-slim python3 -c 'import doctr'

  pytest-api:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.9"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Build & run docker
        run: cd api && make lock && make run
      - name: Ping server
        run: wget --spider --tries=12 http://localhost:8080/docs
      - name: Run docker test
        run: cd api && make test
